export const MONTH_CLOSE_ERRORS = {
  MONTH_NOT_CLOSED: 'MONTH_NOT_CLOSED',
  AMOUNT_MISMATCH: 'AMOUNT_MISMATCH',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  PERIOD_MISMATCH: 'PERIOD_MISMATCH',
  ALREADY_CLOSED: 'ALREADY_CLOSED',
  EMPTY_ALLOCATIONS: 'EMPTY_ALLOCATIONS',
} as const;

export type MonthCloseErrorCode =
  (typeof MONTH_CLOSE_ERRORS)[keyof typeof MONTH_CLOSE_ERRORS];
