name: Create Release Tag

on:
  pull_request:
    types: [closed]
    branches:
      - production

jobs:
  tag:
    name: Create Git Tag
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.OWNER_AUTH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Print new tag
        run: |
          echo "New tag created: ${{ steps.tag_version.outputs.new_tag }}"
